version: '3.9'
services:
    golang.build:
        container_name: golang-mustache
        build:
            context: .
            dockerfile: build/Dockerfile
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - "5000:5000"
