version: '3.9'
services:
    golang.build:
        container_name: golang-mustache
        build:
            context: {{context}}
            dockerfile: Dockerfile
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - "{{port}}:{{port}}"
        {{volume}}
        {{network}}
    {{stubs}}

{{volume-instance}}
  
{{network-instance}}