version: '3.9'
services:
    node-app:
        container_name: node-app-container
        build:
            context: .
            dockerfile: build/Dockerfile
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - "{{port}}:{{port}}"
        networks:
            - mustache
    {{stubs}}

volumes:
    mustache-volume:
  
networks:
    mustache:
        driver: bridge
