version: '3.9'
services:
    golang.build:
        container_name: golang-mustache
        build:
            context: {{context}}
            dockerfile: Dockerfile
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        volumes:
            - '.:/var/www/html'
        networks:
            - mustache
{{depends}}
{{services}}
networks:
    mustache:
        driver: bridge
{{volumes}}